import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";

export type ReportPdfFlag = {
  title: string;
  description: string;
  severity: string;
  quote: string;
};

export type ReportPdfInput = {
  domain: string;
  score: number | null;
  verdict: string | null;
  summary: string | null;
  flags: ReportPdfFlag[];
};

function severityRank(s: string): number {
  const m: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3 };
  return m[String(s).toLowerCase()] ?? 4;
}

function sortFlags(flags: ReportPdfFlag[]): ReportPdfFlag[] {
  return [...flags].sort((a, b) => severityRank(a.severity) - severityRank(b.severity));
}

function wrapLines(text: string, font: PDFFont, size: number, maxWidth: number): string[] {
  const paragraphs = text.replace(/\r/g, "").split("\n");
  const out: string[] = [];
  for (const para of paragraphs) {
    if (para === "") {
      out.push("");
      continue;
    }
    const words = para.split(/\s+/);
    let line = "";
    for (const word of words) {
      const test = line ? `${line} ${word}` : word;
      if (font.widthOfTextAtSize(test, size) <= maxWidth) line = test;
      else {
        if (line) out.push(line);
        line = word;
      }
    }
    if (line) out.push(line);
  }
  return out;
}

export async function buildReportPdfBytes(input: ReportPdfInput): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const margin = 50;
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  let page: PDFPage = doc.addPage();
  const pageWidth = page.getWidth();
  const pageHeight = page.getHeight();
  const maxW = pageWidth - margin * 2;
  let y = pageHeight - margin;

  const lineH = (size: number) => size * 1.28;

  const ensureSpace = (needed: number) => {
    if (y - needed < margin) {
      page = doc.addPage();
      y = page.getHeight() - margin;
    }
  };

  const drawParagraph = (text: string, size: number, bold = false) => {
    const f = bold ? fontBold : font;
    const lines = wrapLines(text, f, size, maxW);
    const lh = lineH(size);
    for (const line of lines) {
      ensureSpace(lh);
      page.drawText(line.length ? line : " ", {
        x: margin,
        y: y - size,
        size,
        font: f,
        color: rgb(0.15, 0.15, 0.18),
      });
      y -= lh;
    }
    y -= 3;
  };

  drawParagraph("FlagLink AI — Terms report", 15, true);
  drawParagraph(`Source: ${input.domain}`, 11);
  drawParagraph(`Score: ${input.score ?? "—"} / 100`, 11);
  drawParagraph(`Verdict: ${input.verdict ?? "—"}`, 11);
  if (input.summary?.trim()) {
    drawParagraph("Summary", 11, true);
    drawParagraph(input.summary.trim(), 10);
  }
  drawParagraph("Red flags", 12, true);
  const sorted = sortFlags(input.flags);
  if (sorted.length === 0) {
    drawParagraph("No flags listed for this scan.", 10);
  } else {
    for (const f of sorted) {
      const block = `[${String(f.severity).toUpperCase()}] ${f.title}${f.description ? `\n${f.description}` : ""}${f.quote ? `\nQuote: ${f.quote}` : ""}`;
      drawParagraph(block, 9);
    }
  }
  drawParagraph(
    "This report is generated by FlagLink AI for informational purposes only. It is not legal advice.",
    8
  );

  return doc.save();
}
